"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const root = path.resolve(__dirname, "..");
const html = fs.readFileSync(path.join(root, "index.html"), "utf8");
const script = fs.readFileSync(path.join(root, "app.js"), "utf8");
const customModule = fs.readFileSync(path.join(root, "beam-custom-section.js"), "utf8");
const styles = fs.readFileSync(path.join(root, "styles.css"), "utf8");
const outline = fs.readFileSync(path.join(root, "SC_HANDBOOK.md"), "utf8");

const beamFamilyButtons = [...html.matchAll(/class="beam-family(?: active)?"[^>]+data-beam-family="([^"]+)"/g)].map(match => match[1]);
assert.deepEqual(beamFamilyButtons, ["ub", "uc", "pfc", "chs", "rhs", "shs", "ea", "rod"]);
assert.match(html, /<select id="beamFamily"[^>]+hidden[^>]+tabindex="-1"/);
assert.match(script, /document\.querySelectorAll\("\.beam-family"\).*setBeamFamily\(button\.dataset\.beamFamily\)/s);
assert.doesNotMatch(script, /beamSource|setBeamSource/);
assert.doesNotMatch(html, />Custom Rod<\/button>/);
assert.doesNotMatch(html, /id="beamCustomFamily"/);
assert.doesNotMatch(html, /id="beamCustomDepth"/);
assert.doesNotMatch(html, /id="beamCustomRodDiameter"/);
assert.doesNotMatch(html, /id="beamCustomFields"/);
assert.match(html, /id="beamDimensionOverride" type="checkbox"/);
assert.match(html, /id="beamDimensionFields" hidden/);
assert.match(html, /id="beamCustomMaterialField" hidden/);
assert.match(html, /id="beamCustomMaterialForm" aria-label="Custom section material basis"/);
assert.match(html, /<b>Material properties<\/b>/);
assert.match(html, /id="beamGradeField"[\s\S]*id="beamFyInput"[\s\S]*id="beamFywInput"[\s\S]*id="beamFuInput"/);
assert.doesNotMatch(html, /Override material values/);
assert.match(html, /beam-custom-section\.js\?v=/);
["beamDimID", "beamDimPfcD", "beamDimChsD", "beamDimRhsD", "beamDimShsB", "beamDimEaB", "beamDimRodD"].forEach(id => {
  assert.match(html, new RegExp(`id="${id}"`));
});
assert.match(script, /function beamDimensionOverrideActive\(\)/);
assert.match(script, /function beamCustomSection\(\)/);
assert.match(script, /BeamCustomSection\.build\(beamFamily, beamCustomDimensions\(\)\)/);
assert.match(script, /BeamCustomSection\.resolveMaterial/);
assert.match(script, /\$\("beamSectionField"\)\.hidden = active/);
assert.match(customModule, /SectionGeometry\.symmetricI\(d, bf, tw, tf\)/);
assert.match(customModule, /SectionGeometry\.channel\(d, bf, tw, tf\)/);
assert.match(customModule, /SectionGeometry\.circularHollow\(D, t\)/);
assert.match(customModule, /SectionGeometry\.rectangularHollow\(b, d, t\)/);
assert.match(customModule, /SectionGeometry\.equalAngle\(b, t\)/);
assert.match(customModule, /SectionGeometry\.circle\(D\)/);
assert.match(script, /customDimensions \|\| momentOverride[\s\S]*BeamSectionReconciliation\.deriveProject/);
assert.doesNotMatch(html, /class="beam-material-state"/);
assert.match(html, /id="beamMaterialStatus" class="input-source-status"/);
assert.match(script, /const materialOverride = momentOverride \|\| webOverride \|\| ultimateOverride/);
assert.match(script, /fuInput >= maximumYield/);
assert.match(script, /f<sub>u<\/sub> confirms the material record and is not used in the current section moment or shear equations/);
assert.match(customModule, /fu: moment\?\.fu \?\? null/);
assert.doesNotMatch(html, /beam-type-switch/);
assert.match(script, /button\.setAttribute\("aria-pressed", String\(active\)\)/);
assert.match(styles, /\.beam-family-switch \{[^}]*grid-template-columns: repeat\(8, minmax\(0, 1fr\)\)/);
assert.match(outline, /one horizontal segmented row on the desktop Beam page/);
assert.match(outline, /Keep `Custom dimensions` inside each selected family/);
assert.match(outline, /PFC: x-x moment.*custom Load A \/ B remains `Not evaluated`/);
assert.match(outline, /Do not add a separate Custom family or a standalone Custom Round Bar tab state/);
assert.match(outline, /hide the catalogue designation control and remove it from the active calculation state/);
assert.match(outline, /EA: Custom dimensions is disabled in the Beam tab/);
assert.match(outline, /one always-visible `Material properties` group/);
assert.match(outline, /Do not hide the adopted strengths inside an override disclosure/);
assert.doesNotMatch(html, /AS 4100:2020 Cl\./);
assert.doesNotMatch(script, /AS 4100:2020 Cl\./);
assert.match(script, /&lambda;<sub>v<\/sub> = \(d<sub>p<\/sub>\/t<sub>w<\/sub>\)&radic;\(f<sub>y,w<\/sub>\/250\)/);
assert.match(script, /&alpha;<sub>v<\/sub> = min\[1, \(82\/&lambda;<sub>v<\/sub>\)<sup>2<\/sup>\]/);
assert.match(script, /V<sub>v<\/sub> = min\[V<sub>u<\/sub>, 2V<sub>u<\/sub>\/\(0\.9 \+ &rho;\)\]/);
assert.match(script, /&phi;V<sub>v<\/sub> = 0\.90V<sub>v<\/sub>/);
assert.match(script, /&lambda;<sub>v<\/sub> = \(\$\{formatBeamNumber\(section\.d1, 1\)\}\/\$\{formatBeamNumber\(section\.tw, 1\)\}\)/);
assert.match(script, /V<sub>v<\/sub> = min\(\$\{fixed\(hollowWeb\.shearYieldCapacity\)\}, \$\{fixed\(hollowWeb\.nonUniformCapacity\)\}\) = \$\{fixed\(hollowWeb\.nominalCapacity\)\} kN/);
assert.match(script, /reference: "AS 4100 Cl\. 5\.2\.1"/);
assert.doesNotMatch(script, /selection: `\$\{directionLabel\}\$\{loadCaseHtml\}`/);
assert.match(script, /formula: momentAvailable \? `&phi;M<sub>s\$\{symbol\}<\/sub> = &phi;f<sub>y,m<\/sub>Z<sub>e\$\{symbol\}<\/sub>`/);
assert.match(script, /reference: "AS 4100 Cl\. 5\.2\.2 to AS 4100 Cl\. 5\.2\.5"/);
assert.match(script, /reference: interactionAvailable \? "AS 4100 Cl\. 5\.12\.3" : ""/);
assert.match(script, /function formatBeamUtilisation\(value\)/);
assert.match(script, /Math\.abs\(value - 1\) < 1e-9\) return "1\.00"/);
assert.match(script, /value > 1 && value < 1\.005\) return ">1\.00"/);
assert.match(script, /value < 1 && value > 0\.995\) return "<1\.00"/);
assert.match(script, /function formatBeamInteractionRatio\(value\)/);
assert.match(script, /function formatBeamInteractionFactor\(value\)/);
assert.match(script, /formatBeamInteractionRatio\(momentRatio\)/);
assert.match(script, /formatBeamInteractionFactor\(interaction\.factor\)/);
assert.match(script, /formatBeamUtilisation\(shearRatio\)/);
assert.match(html, /id="beamUtilisation">&mdash;<\/strong><small id="beamStatus" class="check">No design action/);
assert.match(script, /\$\("beamUtilisation"\)\.textContent = !hasDemand \? "—"/);
assert.match(script, /!momentAvailable \|\| !allDemandPathsAvailable \|\| !hasDemand \? "check"/);
assert.match(outline, /For every evaluated shear path, the trace must show the governing formula before substitution/);
assert.match(outline, /Do not skip from geometry directly to the final `phi Vv`/);

console.log("Beam calculation-trace contract tests passed.");
